# Generated by Django 3.0.3 on 2020-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200223_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=22, verbose_name='Título')),
                ('descricao', models.CharField(max_length=85, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Laptop/Phone'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas')], max_length=20, verbose_name='Icone')),
                ('lado', models.CharField(choices=[('box-item wow fadeInLeft', 'Esquerda'), ('box-item wow fadeInRight', 'Direita')], max_length=25, verbose_name='Lado')),
                ('posicao', models.CharField(choices=[('0.3s', '1'), ('0.6s', '2'), ('0.9s', '3')], max_length=5, verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=35, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(max_length=110, verbose_name='Bio'),
        ),
    ]
