# Generated by Django 3.0.3 on 2020-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200224_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='posicao',
        ),
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Laptop/Phone'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas')], max_length=20, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Laptop/Phone'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas')], max_length=20, verbose_name='Icone'),
        ),
    ]
